name: Release

# Run on every commit tag which begins with "v"
on:
  push:
    branches:
    - master
    tags:
      - "v*"

# Automatically create a GitHub Release with details from previous commits
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
  deploy-binaries:
    name: Publish for "${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: Brigitta
            asset_name: Brigitta-linux-amd64
          - os: windows-latest
            artifact_name: Brigitta.exe
            asset_name: Brigitta-windows-amd64
          - os: macos-latest
            artifact_name: Brigitta
            asset_name: Brigitta-macos-amd64
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: dotnet publish -c Release -o Brigitta Brigitta/Brigitta.csproj
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        file: "Brigitta/${{ matrix.artifact_name }}"
        asset_name: "${{ matrix.asset_name }}"
        