name: Continuous Deployment

# Run on every commit tag which begins with "v" 
on:
  push:
    tags:
      - "v*"

# Automatically create a GitHub Release with details from previous commits
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
  deploy-binaries:
    name: Publish for "${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: brigitta-linux-amd64
            asset_name: brigitta-linux-amd64.zip
          - os: windows-latest
            artifact_name: brigitta-windows-amd64
            asset_name: brigitta-windows-amd64.zip
          - os: macos-latest
            artifact_name: brigitta-macos-amd64
            asset_name: brigitta-macos-amd64.zip
    steps:
    - uses: actions/checkout@v2
    - name: Publish
      run: dotnet publish -c Release -o BrigittaApp/${{ matrix.artifact_name }} Brigitta/Brigitta.csproj
    - name: Archive published binary
      uses: thedoctor0/zip-release@main
      with:
        type: zip
        filename: "${{ matrix.asset_name }}"
        path: "BrigittaApp/${{ matrix.artifact_name }}"
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        file: "${{ matrix.asset_name }}"
        asset_name: "${{ matrix.asset_name }}"
        